### ISSUE TITLE
Not compatible with newest Timber version

### ISSUE THREAD

**Issue by biafra23** [arcao/slf4j-timber#4]
Since version 4.0.0 Timber is not distributed as a jar anymore. It is now an aar. Apparently the Android build system does not allow jars to depend on aars. I think the easiest way to handle this is to make slf4j-timbers release artifact also an aar. I tried it, and t seems to work. 
1. Change the packaging from jar to aar
2. Add the android-maven-plugin to the build/plugins section

Let me know, if you want a pull request for this. I did these changes to 2.2.0-SNAPSHOT on master.

**Comment by arcao** [comment]
I migrated to Gradle build system. Try new version 3.0.

**Comment by biafra23** [comment]
Thank you!
