### ISSUE TITLE
.jar file 

### ISSUE THREAD

**Issue by hoangduchuu** [arcao/slf4j-timber#9]
Hi @arcao , I can not download *.jar
Please re-up this file.
Thanks you!

**Comment by arcao** [comment]
I attached `jar` and `aar` files to [Releases](https://github.com/arcao/slf4j-timber/releases). But I recommend to define `slf4j-timber` as downloadable dependency from Maven Central or JCenter repository as is described in [Readme](https://github.com/arcao/slf4j-timber/blob/master/README.md).
